import { Header } from "@/components/layout/header";
import { Providers } from "@/features/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body
                className={cn(
                    geistMono.variable,
                    geistSans.variable,
                    "antialiased h-full flex flex-col",
                )}
                suppressHydrationWarning
            >
                <Providers>
                    <Header />
                    <NuqsAdapter>
                        <main className="flex-1">{children}</main>
                    </NuqsAdapter>
                </Providers>
            </body>
        </html>
    );
}
